from src.DirectedWeightedGraph.graphAlgoFile import GraphAlgo
# g = GraphAlgo()
# g.load_from_json("../data/A2.json")
# g.save_to_json("../data/ohad_check.json")
# g.graph.remove_node(1)
# print(g.is_connected())
graph_algo_to_plot_check: GraphAlgo = GraphAlgo()
x= graph_algo_to_plot_check.load_from_json("../data/A3.json")
print(x)
y = graph_algo_to_plot_check.save_to_json("C:/Users/shira/Desktop/bdika2.json")
print(y)
graph_algo_to_plot_check.plot_graph()
